/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/admin/users/{userID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Toggle admin status
		 * @description Admin-only endpoint to grant (GET) or revoke (DELETE) admin privileges for a user.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User UUID */
					userID: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/application_statuses': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List current user's application statuses
		 * @description Returns all application statuses belonging to the authenticated user.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Include archived statuses */
					include_archived?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationStatusResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create application status
		 * @description Creates a new application status for the authenticated user.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Application status payload */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.applicationStatusRequest'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationStatusResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/application_statuses/{statusID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get application status
		 * @description Returns a single application status. Users can read their own; admins can read any.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Application status ID */
					statusID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationStatusResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		/**
		 * Update application status
		 * @description Updates an existing application status. Only the owner or an admin can update it.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Application status ID */
					statusID: number;
				};
				cookie?: never;
			};
			/** @description Updated application status */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.applicationStatusRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationStatusResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete application status
		 * @description Deletes an application status. If soft_delete=true, performs a soft delete (and cascades to linked job applications). Otherwise archives the status. Only the owner or an admin can delete it.
		 */
		delete: {
			parameters: {
				query?: {
					/** @description Soft deletes the application status, if set to false it archives the status instead */
					soft_delete?: boolean;
				};
				header?: never;
				path: {
					/** @description Application status ID */
					statusID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/application_statuses/{statusID}/unarchive': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Unarchive application status
		 * @description Restores an archived application status. Only the owner or an admin can unarchive it.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Application status ID */
					statusID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/login': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Login
		 * @description Authenticates a user. For web clients the response includes two Set-Cookie headers: access_token (HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=300) and refresh_token (HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=5184000). TUI clients receive the tokens in the response body. The X-Jat-Client-Type header is required by the server middleware but is set automatically by the generated web client.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Login credentials */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.userLoginRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						/** @description access_token=<jwt>; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=300 AND refresh_token=<token>; HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=5184000 */
						'Set-Cookie'?: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.loginResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/logout': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Logout
		 * @description Revokes the current refresh token. For web clients the refresh_token cookie is cleared by setting Max-Age=-1 on the response. The X-Jat-Client-Type header is required by the server middleware but is set automatically by the generated web client.
		 */
		post: {
			parameters: {
				query?: never;
				header?: {
					/** @description Bearer refresh token (TUI clients) */
					Authorization?: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						/** @description refresh_token=; HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=-1 */
						'Set-Cookie'?: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/refresh_token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Refresh access token
		 * @description Issues a new access token from a valid refresh token. Web clients get a new access_token cookie (path /api, MaxAge=300); TUI clients get the token in the response body. The X-Jat-Client-Type header is required by the server middleware but is set automatically by the generated web client.
		 */
		get: {
			parameters: {
				query?: never;
				header?: {
					/** @description Bearer refresh token (TUI clients) */
					Authorization?: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						/** @description access_token=<jwt>; HttpOnly; Secure; SameSite=Strict; Path=/api; Max-Age=300 */
						'Set-Cookie'?: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: string;
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/auth/revoke_token': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Revoke refresh token
		 * @description Revokes the refresh token passed in the request. For web clients the refresh_token cookie is cleared by setting Max-Age=-1 on the response. The X-Jat-Client-Type header is required by the server middleware but is set automatically by the generated web client.
		 */
		get: {
			parameters: {
				query?: never;
				header?: {
					/** @description Bearer refresh token (TUI clients) */
					Authorization?: string;
				};
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						/** @description refresh_token=; HttpOnly; Secure; SameSite=Strict; Path=/api/auth; Max-Age=-1 */
						'Set-Cookie'?: string;
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/company': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all companies
		 * @description Returns every company in the system. (returns 403 if a non admin user passes the preload_users query param)
		 */
		get: {
			parameters: {
				query?: {
					/** @description Include a count of user applications for this company */
					user_count?: boolean;
					/** @description Include user data for the creation/edits of companies (admin only) */
					preload_users?: boolean;
					/** @description Include a count of total applications (global) for this company */
					total_count?: boolean;
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.companyResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create company
		 * @description Creates a new company.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody: components['requestBodies']['api.companyBodyRequest'];
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.companyResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Conflict */
				409: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/company/{companyID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get company
		 * @description Returns a single company by ID.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Include a count of user applications for this company */
					user_count?: boolean;
					/** @description Include a count of total applications (global) for this company */
					total_count?: boolean;
				};
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.companyResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		/**
		 * Update company
		 * @description Updates an existing company.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
				};
				cookie?: never;
			};
			requestBody: components['requestBodies']['api.companyBodyRequest'];
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.companyResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete company
		 * @description Admin-only. Soft-deletes a company by ID.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/company/{companyID}/count': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Count Company Job Applications
		 * @description Counts the Job Applications a company has company ID. If the total_count query param is true it returns the total applications for a company, otherwise it returns the total applications for the user
		 */
		get: {
			parameters: {
				query?: {
					/** @description Include a count of total applications (global) for this company */
					total_count?: boolean;
				};
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.apiCountResult'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/company/{companyID}/history': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get history of changes to a company
		 * @description Returns the history of changes to a company record (admin only)
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.companyChangeHistoryResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/company/{companyID}/history/{changeID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Reverts a company change record
		 * @description Reverts a change that was made to a company record (admin only)
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Company ID */
					companyID: number;
					/** @description Change ID */
					changeID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/health': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health check
		 * @description Returns a success message if the database is reachable.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: string;
						};
					};
				};
				/** @description Internal Server Error */
				500: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/initialized': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Check initialization state
		 * @description Returns whether the server has been initialized (first admin created). This is used by the web UI to decide between the create-account and login flows.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.systemResponse'];
						};
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/initialized/set': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Mark service as initialized
		 * @description Sets the server initialized flag. Only the first admin can call this.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List current user's job applications
		 * @description Returns all job applications belonging to the authenticated user.
		 */
		get: {
			parameters: {
				query?: {
					/** @description Filter by Company IDs */
					company_id?: number[];
					/** @description Filter by Status IDs */
					status_id?: number[];
				};
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create job application
		 * @description Creates a new job application for the authenticated user.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Job application payload */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.applicationRequest'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{jobID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get job application
		 * @description Returns a single job application. Users can read their own; admins can read any.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		/**
		 * Delete job application
		 * @description Soft-deletes a job application. Only the owner or an admin can delete it.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{jobID}/history': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get job application status history
		 * @description Returns the status change history for a single job application. Users can read their own; admins can read any.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationStatusHistoryResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{jobID}/notes': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List notes for a job application
		 * @description Returns all notes belonging to a specific job application.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.noteData'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		/**
		 * Create job application note
		 * @description Adds a note to a job application.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
				};
				cookie?: never;
			};
			requestBody: components['requestBodies']['api.noteCreateRequest'];
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.noteData'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{jobID}/notes/{noteID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get job application note
		 * @description Returns a single note from a job application.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
					/** @description Note ID */
					noteID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.noteData'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		/**
		 * Update job application note
		 * @description Updates an existing note on a job application.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
					/** @description Note ID */
					noteID: number;
				};
				cookie?: never;
			};
			requestBody: components['requestBodies']['api.noteCreateRequest'];
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.noteData'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		/**
		 * Delete job application note
		 * @description Deletes a note from a job application.
		 */
		delete: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
					/** @description Note ID */
					noteID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/jobs/{jobID}/status/{statusID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/**
		 * Update job application status
		 * @description Changes the status of a job application.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description Job application ID */
					jobID: number;
					/** @description Application status ID */
					statusID: number;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.applicationResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/users': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List all users
		 * @description Admin-only endpoint that returns every user.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.userCreateResponse'][];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		/**
		 * Update current user
		 * @description Updates the authenticated user's profile.
		 */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description Updated user fields */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.userCreateRequest'];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.userCreateResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		/**
		 * Create user
		 * @description Creates the first user. If no admin exists and the service is not initialized, the new user becomes the first admin.
		 */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			/** @description User creation payload */
			requestBody: {
				content: {
					'application/json': components['schemas']['api.userCreateRequest'];
				};
			};
			responses: {
				/** @description Created */
				201: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.userCreateResponse'];
						};
					};
				};
				/** @description Bad Request */
				400: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/users/me': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get current user
		 * @description Returns the currently authenticated user. This is the only user endpoint that web clients can call on page load without knowing their own UUID.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path?: never;
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.userCreateResponse'];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	'/users/{userID}': {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get a user
		 * @description Returns a single user. Users can read their own record; admins can read any record.
		 */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description User UUID */
					userID: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'] & {
							data?: components['schemas']['api.userCreateResponse'];
						};
					};
				};
				/** @description Unauthorized */
				401: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Forbidden */
				403: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
				/** @description Not Found */
				404: {
					headers: {
						[name: string]: unknown;
					};
					content: {
						'application/json': components['schemas']['api.apiResponse'];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		'api.apiCountResult': {
			count: number;
		};
		'api.apiResponse': {
			data?: unknown;
			message: string;
			ok: boolean;
		};
		'api.applicationRequest': {
			company_id: number;
			created_at: string;
			status_id: number;
			title: string;
			url: string;
		};
		'api.applicationResponse': {
			company: components['schemas']['api.companyResponse'];
			created_at: string;
			id: number;
			status: components['schemas']['api.applicationStatusResponse'];
			title: string;
			updated_at: string;
			url: string;
			user_id: string;
		};
		'api.applicationStatusHistoryResponse': {
			application_id: number;
			created_at: string;
			id: number;
			new_status: components['schemas']['api.applicationStatusResponse'];
			old_status?: components['schemas']['api.applicationStatusResponse'];
		};
		'api.applicationStatusRequest': {
			kind: string;
			status: string;
		};
		'api.applicationStatusResponse': {
			archived: boolean;
			created_at: string;
			id: number;
			kind: string;
			status: string;
			updated_at: string;
			user_id?: string;
		};
		'api.companyBodyRequest': {
			name: string;
			website?: string;
		};
		'api.companyChangeHistoryResponse': {
			changed_by: components['schemas']['api.userCreateResponse'];
			company_id: number;
			created_at: string;
			id: number;
			new_name: string;
			new_website: string;
			old_name: string;
			old_website: string;
			reverted: boolean;
		};
		'api.companyResponse': {
			created_at: string;
			created_by_user?: components['schemas']['api.userCreateResponse'];
			id: number;
			name: string;
			total_count?: number;
			updated_at: string;
			updated_by_user?: components['schemas']['api.userCreateResponse'];
			user_count?: number;
			website?: string;
		};
		'api.loginResponse': {
			email: string;
			refresh_token?: string;
			token?: string;
			user_id: string;
		};
		'api.noteCreateRequest': {
			body: string;
		};
		'api.noteData': {
			body: string;
			created_at: string;
			id: number;
			job_id: number;
			status: components['schemas']['api.applicationStatusResponse'];
			updated_at: string;
			user_id: string;
		};
		'api.systemResponse': {
			initialized?: boolean;
		};
		'api.userCreateRequest': {
			email: string;
			password: string;
			username: string;
		};
		'api.userCreateResponse': {
			created_at: string;
			default_status_id?: number;
			email: string;
			is_admin?: boolean;
			updated_at: string;
			user_id: string;
			username: string;
		};
		'api.userLoginRequest': {
			email: string;
			password: string;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: {
		/** @description Note body */
		'api.noteCreateRequest': {
			content: {
				'application/json': components['schemas']['api.noteCreateRequest'];
			};
		};
		/** @description Company payload */
		'api.companyBodyRequest': {
			content: {
				'application/json': components['schemas']['api.companyBodyRequest'];
			};
		};
	};
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
