package services

import (
	"errors"
	"time"

	"github.com/filz0r/jat/internal/auth"
	"github.com/filz0r/jat/internal/database"
	"github.com/google/uuid"
)

// TODO: needs cleanup from AI SLOP

// CreateRefreshToken issues a new refresh token for userID. The token value
// itself is generated by auth.MakeRefreshToken (64-hex-char random string).
func (sm *ServiceManager) CreateRefreshToken(
	userID uuid.UUID,
	ttl time.Duration,
) (database.RefreshToken, error) {
	if sm.db == nil {
		return database.RefreshToken{}, errors.New("database not initialized")
	}
	token := database.RefreshToken{
		Token:     auth.MakeRefreshToken(),
		UserID:    userID,
		ExpiresAt: time.Now().Add(ttl),
	}
	result := sm.db.Create(&token)
	return token, result.Error
}

// GetValidRefreshToken returns the token record only when it exists, has not
// been revoked (ExpiredAt unset) and has not lapsed.
func (sm *ServiceManager) GetValidRefreshToken(token string) (database.RefreshToken, error) {
	if sm.db == nil {
		return database.RefreshToken{}, errors.New("database not initialized")
	}
	var refreshToken database.RefreshToken
	result := sm.db.Where("token = ?", token).First(&refreshToken)
	if result.Error != nil {
		return database.RefreshToken{}, result.Error
	}
	if refreshToken.ExpiredAt != nil {
		return database.RefreshToken{}, errors.New("refresh token has been revoked")
	}
	if time.Now().After(refreshToken.ExpiresAt) {
		return database.RefreshToken{}, errors.New("refresh token has expired")
	}
	return refreshToken, nil
}

// RevokeRefreshToken marks a token as expired so it can no longer be used;
// the row is kept for audit purposes.
func (sm *ServiceManager) RevokeRefreshToken(token string) error {
	if sm.db == nil {
		return errors.New("database not initialized")
	}
	result := sm.db.Model(&database.RefreshToken{}).
		Where("token = ?", token).
		Update("expired_at", time.Now())
	return result.Error
}

// DeleteExpiredRefreshTokens purges lapsed and revoked rows, for periodic
// cleanup once refresh tokens are in use.
func (sm *ServiceManager) DeleteExpiredRefreshTokens() error {
	if sm.db == nil {
		return errors.New("database not initialized")
	}
	result := sm.db.
		Where("expires_at < ? OR expired_at IS NOT NULL", time.Now()).
		Delete(&database.RefreshToken{})
	return result.Error
}

func (sm *ServiceManager) UpdateRefreshToken(token string, newTimeStamp time.Time) error {
	if sm.db == nil {
		return errors.New("database not initialized")
	}
	var refreshToken database.RefreshToken
	result := sm.db.Where("token = ?", token).First(&refreshToken)
	if result.Error != nil {
		return result.Error
	}
	refreshToken.UpdatedAt = newTimeStamp
	result = sm.db.Save(&refreshToken)
	return result.Error
}
