/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppAccountIndexRouteImport } from './routes/_app.account.index'
import { Route as AppAdminIndexRouteImport } from './routes/_app.admin.index'
import { Route as AppApplication_statusIndexRouteImport } from './routes/_app.application_status.index'
import { Route as AppApplication_statusStatusIDRouteImport } from './routes/_app.application_status.$statusID'
import { Route as AppCompaniesIndexRouteImport } from './routes/_app.companies.index'
import { Route as AppCompaniesCompanyIDRouteImport } from './routes/_app.companies.$companyID'
import { Route as AppJobsIndexRouteImport } from './routes/_app.jobs.index'
import { Route as AppJobsJobIDRouteImport } from './routes/_app.jobs.$jobID'
import { Route as AppJobsNewRouteImport } from './routes/_app.jobs.new'
import { Route as AppAdminUsersIndexRouteImport } from './routes/_app.admin.users.index'
import { Route as AppAdminUsersUserIDRouteImport } from './routes/_app.admin.users.$userID'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIndexRoute = AppAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AppRoute,
} as any)
const AppApplication_statusIndexRoute =
  AppApplication_statusIndexRouteImport.update({
    id: '/application_status/',
    path: '/application_status/',
    getParentRoute: () => AppRoute,
  } as any)
const AppApplication_statusStatusIDRoute =
  AppApplication_statusStatusIDRouteImport.update({
    id: '/application_status/$statusID',
    path: '/application_status/$statusID',
    getParentRoute: () => AppRoute,
  } as any)
const AppCompaniesIndexRoute = AppCompaniesIndexRouteImport.update({
  id: '/companies/',
  path: '/companies/',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIDRoute = AppCompaniesCompanyIDRouteImport.update({
  id: '/companies/$companyID',
  path: '/companies/$companyID',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsIndexRoute = AppJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsJobIDRoute = AppJobsJobIDRouteImport.update({
  id: '/jobs/$jobID',
  path: '/jobs/$jobID',
  getParentRoute: () => AppRoute,
} as any)
const AppJobsNewRoute = AppJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersIndexRoute = AppAdminUsersIndexRouteImport.update({
  id: '/admin/users/',
  path: '/admin/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminUsersUserIDRoute = AppAdminUsersUserIDRouteImport.update({
  id: '/admin/users/$userID',
  path: '/admin/users/$userID',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/application_status/$statusID': typeof AppApplication_statusStatusIDRoute
  '/companies/$companyID': typeof AppCompaniesCompanyIDRoute
  '/jobs/$jobID': typeof AppJobsJobIDRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/account/': typeof AppAccountIndexRoute
  '/admin/': typeof AppAdminIndexRoute
  '/application_status/': typeof AppApplication_statusIndexRoute
  '/companies/': typeof AppCompaniesIndexRoute
  '/jobs/': typeof AppJobsIndexRoute
  '/admin/users/$userID': typeof AppAdminUsersUserIDRoute
  '/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/': typeof AppIndexRoute
  '/application_status/$statusID': typeof AppApplication_statusStatusIDRoute
  '/companies/$companyID': typeof AppCompaniesCompanyIDRoute
  '/jobs/$jobID': typeof AppJobsJobIDRoute
  '/jobs/new': typeof AppJobsNewRoute
  '/account': typeof AppAccountIndexRoute
  '/admin': typeof AppAdminIndexRoute
  '/application_status': typeof AppApplication_statusIndexRoute
  '/companies': typeof AppCompaniesIndexRoute
  '/jobs': typeof AppJobsIndexRoute
  '/admin/users/$userID': typeof AppAdminUsersUserIDRoute
  '/admin/users': typeof AppAdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/_app/': typeof AppIndexRoute
  '/_app/application_status/$statusID': typeof AppApplication_statusStatusIDRoute
  '/_app/companies/$companyID': typeof AppCompaniesCompanyIDRoute
  '/_app/jobs/$jobID': typeof AppJobsJobIDRoute
  '/_app/jobs/new': typeof AppJobsNewRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/admin/': typeof AppAdminIndexRoute
  '/_app/application_status/': typeof AppApplication_statusIndexRoute
  '/_app/companies/': typeof AppCompaniesIndexRoute
  '/_app/jobs/': typeof AppJobsIndexRoute
  '/_app/admin/users/$userID': typeof AppAdminUsersUserIDRoute
  '/_app/admin/users/': typeof AppAdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/setup'
    | '/application_status/$statusID'
    | '/companies/$companyID'
    | '/jobs/$jobID'
    | '/jobs/new'
    | '/account/'
    | '/admin/'
    | '/application_status/'
    | '/companies/'
    | '/jobs/'
    | '/admin/users/$userID'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/setup'
    | '/'
    | '/application_status/$statusID'
    | '/companies/$companyID'
    | '/jobs/$jobID'
    | '/jobs/new'
    | '/account'
    | '/admin'
    | '/application_status'
    | '/companies'
    | '/jobs'
    | '/admin/users/$userID'
    | '/admin/users'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/register'
    | '/setup'
    | '/_app/'
    | '/_app/application_status/$statusID'
    | '/_app/companies/$companyID'
    | '/_app/jobs/$jobID'
    | '/_app/jobs/new'
    | '/_app/account/'
    | '/_app/admin/'
    | '/_app/application_status/'
    | '/_app/companies/'
    | '/_app/jobs/'
    | '/_app/admin/users/$userID'
    | '/_app/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/': {
      id: '/_app/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AppAdminIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/application_status/': {
      id: '/_app/application_status/'
      path: '/application_status'
      fullPath: '/application_status/'
      preLoaderRoute: typeof AppApplication_statusIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/application_status/$statusID': {
      id: '/_app/application_status/$statusID'
      path: '/application_status/$statusID'
      fullPath: '/application_status/$statusID'
      preLoaderRoute: typeof AppApplication_statusStatusIDRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/': {
      id: '/_app/companies/'
      path: '/companies'
      fullPath: '/companies/'
      preLoaderRoute: typeof AppCompaniesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies/$companyID': {
      id: '/_app/companies/$companyID'
      path: '/companies/$companyID'
      fullPath: '/companies/$companyID'
      preLoaderRoute: typeof AppCompaniesCompanyIDRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/': {
      id: '/_app/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof AppJobsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/$jobID': {
      id: '/_app/jobs/$jobID'
      path: '/jobs/$jobID'
      fullPath: '/jobs/$jobID'
      preLoaderRoute: typeof AppJobsJobIDRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/jobs/new': {
      id: '/_app/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof AppJobsNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/': {
      id: '/_app/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AppAdminUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/users/$userID': {
      id: '/_app/admin/users/$userID'
      path: '/admin/users/$userID'
      fullPath: '/admin/users/$userID'
      preLoaderRoute: typeof AppAdminUsersUserIDRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppApplication_statusStatusIDRoute: typeof AppApplication_statusStatusIDRoute
  AppCompaniesCompanyIDRoute: typeof AppCompaniesCompanyIDRoute
  AppJobsJobIDRoute: typeof AppJobsJobIDRoute
  AppJobsNewRoute: typeof AppJobsNewRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
  AppAdminIndexRoute: typeof AppAdminIndexRoute
  AppApplication_statusIndexRoute: typeof AppApplication_statusIndexRoute
  AppCompaniesIndexRoute: typeof AppCompaniesIndexRoute
  AppJobsIndexRoute: typeof AppJobsIndexRoute
  AppAdminUsersUserIDRoute: typeof AppAdminUsersUserIDRoute
  AppAdminUsersIndexRoute: typeof AppAdminUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppApplication_statusStatusIDRoute: AppApplication_statusStatusIDRoute,
  AppCompaniesCompanyIDRoute: AppCompaniesCompanyIDRoute,
  AppJobsJobIDRoute: AppJobsJobIDRoute,
  AppJobsNewRoute: AppJobsNewRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
  AppAdminIndexRoute: AppAdminIndexRoute,
  AppApplication_statusIndexRoute: AppApplication_statusIndexRoute,
  AppCompaniesIndexRoute: AppCompaniesIndexRoute,
  AppJobsIndexRoute: AppJobsIndexRoute,
  AppAdminUsersUserIDRoute: AppAdminUsersUserIDRoute,
  AppAdminUsersIndexRoute: AppAdminUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
